services:

  django:
    build: ./app
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./app/:/usr/src/app
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    container_name: db
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - django
      - db

volumes:
  postgres_data:
  media:
  static:
